version: '3.1'

services:
  # db:
  #   image: postgres:13-alpine
  #   restart: always
  #   volumes:
  #     - ./volumes/postgres:/var/lib/postgresql:rw,z
  #   expose:
  #     - 5432
  #   ports:
  #     - '15432:5432'
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=test
  #     - POSTGRES_EXTERNAL_PORT=15432
  #     - POSTGRES_DB=archon-db

  redis:
      image: redis:6-alpine
      restart: always
      volumes:
        - ./volumes/redis:/data:rw,z
      ports:
        - '6379:6379'
      expose:
        - 6379
